CREATE TABLE clientes (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          dni VARCHAR(255) NOT NULL,
                          nombre VARCHAR(255) NOT NULL,
                          telefono VARCHAR(255) NOT NULL,

                          CONSTRAINT pk_clientes PRIMARY KEY (id),
                          CONSTRAINT uk_clientes_dni UNIQUE (dni)
);