CREATE TABLE reservas
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id      BIGINT       NOT NULL,
    numero_mesa     INTEGER      NOT NULL,
    numero_personas INTEGER      NOT NULL,
    fecha           DATE         NOT NULL,
    estado_reserva  VARCHAR(255) NOT NULL,

    CONSTRAINT pk_reservas
        PRIMARY KEY (id),

    CONSTRAINT fk_reserva_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes (id),

    CONSTRAINT uk_reserva_mesa_fecha
        UNIQUE (numero_mesa, fecha),

    CONSTRAINT ck_reserva_numero_mesa
        CHECK (numero_mesa > 0),

    CONSTRAINT ck_reserva_numero_personas
        CHECK (numero_personas > 0),

    CONSTRAINT ck_reserva_estado
        CHECK (estado_reserva IN ('PENDIENTE',
                                  'CONFIRMADA',
                                  'CANCELADA'))
);